### ISSUE TITLE
v1.0 milestones

### ISSUE THREAD

**Issue by krispya** [krispya/r3f-character-controller#1]
I'll be updating this as find things that need done.

- [ ] Slope controls
- [ ] Sliding movement
- [ ] Step controls
- [ ] Friction
- [ ] Make colliders work with transforms and animations
- [ ] Make colliders refit if geometry changes
- [ ] Split out Collider library
- [ ] Split out helpers for Drei
- [ ] Split out Input library
